const express = require('express');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const User = require('../models/User');
const QuizResult = require('../models/QuizResult');
const router = express.Router();

// Initialize Gemini AI
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

// @route   POST /api/gemini/analyze-career
// @desc    Get AI-powered career analysis using Gemini
// @access  Private
router.post('/analyze-career', async (req, res) => {
  try {
    const { userId, prompt, includeQuizData = true } = req.body;

    if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'replace-with-your-actual-gemini-api-key') {
      return res.status(400).json({
        success: false,
        message: 'Gemini API key not configured'
      });
    }

    let contextData = '';
    
    if (includeQuizData && userId) {
      // Get user data for context
      const user = await User.findById(userId).select('profile interestTags');
      const latestQuiz = await QuizResult.findOne({ userId })
        .sort({ createdAt: -1 })
        .select('tagScores streamRecommendations careerCompatibility');

      if (user && latestQuiz) {
        contextData = `
User Profile:
- Age: ${user.profile?.age || 'Not specified'}
- Class: ${user.profile?.class || 'Not specified'}
- Gender: ${user.profile?.gender || 'Not specified'}

Interest Analysis (Tag Scores out of 100):
${latestQuiz.tagScores.map(tag => `- ${tag.tag}: ${tag.score}/100`).join('\n')}

Top Stream Recommendations:
${latestQuiz.streamRecommendations.slice(0, 3).map(stream => 
  `- ${stream.stream}: ${stream.score}/100 confidence`
).join('\n')}

Career Compatibility:
${latestQuiz.careerCompatibility.slice(0, 3).map(career => 
  `- ${career.field}: ${career.compatibility}/100 compatibility`
).join('\n')}
        `;
      }
    }

    // Construct the prompt for Gemini
    const fullPrompt = `
You are a career guidance counselor helping students make informed decisions about their education and career paths. 

${contextData ? `Here is the student's assessment data:\n${contextData}\n` : ''}

User Question: ${prompt}

Please provide a comprehensive, personalized response that includes:
1. Specific career recommendations based on the data
2. Educational pathways to achieve those careers
3. Current market trends and opportunities
4. Skills to focus on developing
5. Potential challenges and how to overcome them

Keep the response professional, encouraging, and actionable. Format it in a clear, structured manner.
    `;

    // Get response from Gemini
    const model = genAI.getGenerativeModel({ model: "gemini-pro" });
    const result = await model.generateContent(fullPrompt);
    const response = await result.response;
    const analysis = response.text();

    // Save the analysis if user ID is provided
    if (userId) {
      const user = await User.findById(userId);
      if (user) {
        const latestQuiz = await QuizResult.findOne({ userId }).sort({ createdAt: -1 });
        if (latestQuiz) {
          latestQuiz.geminiInsights = {
            careerSuggestions: analysis,
            educationPath: 'Generated by Gemini AI',
            skillsToFocus: []
          };
          latestQuiz.geminiAnalysisGenerated = true;
          await latestQuiz.save();
        }
      }
    }

    res.json({
      success: true,
      analysis,
      timestamp: new Date(),
      message: 'Career analysis generated successfully'
    });

  } catch (error) {
    console.error('Gemini API error:', error);
    res.status(500).json({
      success: false,
      message: 'Error generating career analysis',
      error: error.message
    });
  }
});

// @route   POST /api/gemini/course-mapping
// @desc    Get detailed course-to-career mapping using Gemini
// @access  Private
router.post('/course-mapping', async (req, res) => {
  try {
    const { course, stream, userInterests = [] } = req.body;

    if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'replace-with-your-actual-gemini-api-key') {
      return res.status(400).json({
        success: false,
        message: 'Gemini API key not configured'
      });
    }

    const prompt = `
Provide a comprehensive career mapping analysis for the course "${course}" in the "${stream}" stream.

${userInterests.length > 0 ? `User's Key Interests: ${userInterests.join(', ')}` : ''}

Please include:

1. CAREER OPPORTUNITIES:
   - List 8-10 specific job roles this course leads to
   - Include both traditional and emerging career paths
   - Mention salary ranges for Indian job market (in LPA)

2. INDUSTRY ANALYSIS:
   - Which industries have the highest demand for these graduates
   - Growth trends and future outlook
   - Geographic hotspots for employment

3. SPECIALIZATION OPTIONS:
   - Postgraduate options and specializations
   - Professional certifications that add value
   - Skill development areas to focus on

4. ENTREPRENEURSHIP OPPORTUNITIES:
   - Business ideas related to this field
   - Startup ecosystem opportunities
   - Required initial investment and skills

5. GOVERNMENT SECTOR OPPORTUNITIES:
   - Relevant government exams (UPSC, SSC, Banking, etc.)
   - PSU opportunities
   - State government positions

6. HIGHER EDUCATION PATHWAYS:
   - Masters degree options in India and abroad
   - Research opportunities (PhD, M.Phil)
   - Study abroad programs and scholarships

7. SKILLS DEVELOPMENT:
   - Technical skills to focus on
   - Soft skills that are crucial
   - Online courses and certifications recommended

Format the response in a structured, easy-to-read manner with clear headings and bullet points.
    `;

    const model = genAI.getGenerativeModel({ model: "gemini-pro" });
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const mapping = response.text();

    res.json({
      success: true,
      course,
      stream,
      mapping,
      generatedAt: new Date(),
      message: 'Course-to-career mapping generated successfully'
    });

  } catch (error) {
    console.error('Gemini course mapping error:', error);
    res.status(500).json({
      success: false,
      message: 'Error generating course mapping',
      error: error.message
    });
  }
});

// @route   POST /api/gemini/skill-recommendations
// @desc    Get personalized skill development recommendations
// @access  Private
router.post('/skill-recommendations', async (req, res) => {
  try {
    const { userId, targetCareer, timeframe = '6 months' } = req.body;

    if (!process.env.GEMINI_API_KEY || process.env.GEMINI_API_KEY === 'replace-with-your-actual-gemini-api-key') {
      return res.status(400).json({
        success: false,
        message: 'Gemini API key not configured'
      });
    }

    let userContext = '';
    if (userId) {
      const user = await User.findById(userId).select('profile interestTags');
      const latestQuiz = await QuizResult.findOne({ userId })
        .sort({ createdAt: -1 })
        .select('tagScores insights');

      if (user && latestQuiz) {
        userContext = `
Student Profile:
- Current Class: ${user.profile?.class || 'Not specified'}
- Age: ${user.profile?.age || 'Not specified'}

Current Skill Strengths (from assessment):
${latestQuiz.tagScores.filter(tag => tag.score > 70).map(tag => 
  `- ${tag.tag}: ${tag.score}/100`
).join('\n')}

Areas for Improvement:
${latestQuiz.tagScores.filter(tag => tag.score < 60).map(tag => 
  `- ${tag.tag}: ${tag.score}/100`
).join('\n')}

Learning Style: ${latestQuiz.insights?.learningStyle || 'Not determined'}
        `;
      }
    }

    const prompt = `
Create a personalized skill development roadmap for someone aiming for a career in "${targetCareer}" within ${timeframe}.

${userContext}

Please provide:

1. SKILL PRIORITIES:
   - Top 5 most important skills to develop
   - Rank them by importance for the target career
   - Estimated time investment for each skill

2. LEARNING ROADMAP:
   - Month-by-month learning plan for ${timeframe}
   - Specific milestones to achieve
   - Progress tracking methods

3. RESOURCE RECOMMENDATIONS:
   - Online courses (Coursera, edX, Udemy, etc.)
   - Books and reading materials
   - YouTube channels and free resources
   - Practical projects to work on

4. CERTIFICATION PATHS:
   - Industry-recognized certifications
   - Cost estimates
   - Difficulty levels and prerequisites

5. PRACTICAL EXPERIENCE:
   - Internship opportunities
   - Volunteer work options
   - Personal projects to build portfolio
   - Networking strategies

6. ASSESSMENT METHODS:
   - How to measure skill development progress
   - Portfolio building strategies
   - Interview preparation tips

Make the recommendations specific, actionable, and tailored to Indian students with limited budgets.
    `;

    const model = genAI.getGenerativeModel({ model: "gemini-pro" });
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const recommendations = response.text();

    res.json({
      success: true,
      targetCareer,
      timeframe,
      recommendations,
      generatedAt: new Date(),
      message: 'Skill recommendations generated successfully'
    });

  } catch (error) {
    console.error('Gemini skill recommendations error:', error);
    res.status(500).json({
      success: false,
      message: 'Error generating skill recommendations',
      error: error.message
    });
  }
});

// @route   GET /api/gemini/status
// @desc    Check Gemini API status and configuration
// @access  Public
router.get('/status', (req, res) => {
  const isConfigured = process.env.GEMINI_API_KEY && 
                      process.env.GEMINI_API_KEY !== 'replace-with-your-actual-gemini-api-key';

  res.json({
    success: true,
    geminiConfigured: isConfigured,
    message: isConfigured ? 'Gemini API is properly configured' : 'Gemini API key not configured'
  });
});

module.exports = router;
